export const quoteResponseSchema = {
  type: "object",
  properties: {
    quote_id: { type: "string" },
    request_id: { type: "string" },
    calculated_at: { type: "string" },
    pricing_version: { type: "string" },
    service_code: { type: "string" },
    service_name: { type: "string" },
    selected_hours: { type: "number" },
    billable_hours: { type: "number" },
    effective_hourly_rate: { type: ["number", "null"] },
    service_time_charge: { type: ["number", "null"] },
    care_coordination_fee: { type: "number" },
    care_charge_before_credits: { type: ["number", "null"] },
    credit_program_enabled: { type: "boolean" },
    credit_discount_requested: { type: "number" },
    credit_discount_max_allowed: { type: ["number", "null"] },
    credit_discount_applied: { type: ["number", "null"] },
    final_care_charge: { type: ["number", "null"] },
    cab_fare: { type: "number" },
    transport_coordination_fee: { type: "number" },
    transport_total: { type: "number" },
    total_customer_payable: { type: ["number", "null"] },
    eligible_credit_earning_spend: { type: ["number", "null"] },
    credit_earn_rate: { type: "number" },
    credit_value_rupees: { type: "number" },
    raw_credits_earned: { type: ["number", "null"] },
    nivraa_credits_earned: { type: ["integer", "null"] },
    credit_expiry_days: { type: "integer" },
    pricing_status: { type: "string" },
    customer_quote: { type: "object" },
    pricing_snapshot: { type: "object" }
  }
} as const;
