import { ServiceConfig } from "../pricing/pricingTypes";

export const serviceMaster: ReadonlyArray<ServiceConfig> = Object.freeze([
  { serviceCode: "HOSPITAL_VISIT", serviceName: "Hospital Visit", category: "Medical Visit", serviceMultiplier: "1.00", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Full journey: home → facility → return / safe handover" },
  { serviceCode: "HOSPITAL_ONLY", serviceName: "Hospital Visit — Concierge at Hospital", category: "Medical Visit", serviceMultiplier: "0.80", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Hospital-only support; reduced travel and handover responsibility" },
  { serviceCode: "CLINIC_VISIT", serviceName: "Clinic Visit", category: "Medical Visit", serviceMultiplier: "0.90", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Shorter, lower-complexity outpatient journey" },
  { serviceCode: "DIAGNOSTIC", serviceName: "Diagnostic Center Visit", category: "Medical Visit", serviceMultiplier: "0.85", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Generally simpler navigation / diagnostic-only workflow" },
  { serviceCode: "HEALTH_CHECKUP", serviceName: "Health Check-up Concierge", category: "Medical Visit", serviceMultiplier: "0.90", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Structured preventive-care journey; moderate coordination" },
  { serviceCode: "ADMISSION", serviceName: "Hospital Admission Concierge", category: "Hospital Support", serviceMultiplier: "1.15", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Higher coordination, documentation and handoff complexity" },
  { serviceCode: "DISCHARGE", serviceName: "Hospital Discharge Concierge", category: "Hospital Support", serviceMultiplier: "1.10", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Higher coordination and post-discharge handover responsibility" },
  { serviceCode: "OVERNIGHT", serviceName: "Overnight Hospital Concierge", category: "Hospital Support", serviceMultiplier: "0.85", pricingMode: "MANUAL", numberOfAngels: 1, active: true, multiplierReason: "Long-duration service; manual pricing should supersede multiplier" },
  { serviceCode: "MULTI_DAY_12H", serviceName: "Multi-Day Hospital Concierge (per 12h shift)", category: "Hospital Support", serviceMultiplier: "0.85", pricingMode: "MANUAL", numberOfAngels: 1, active: true, multiplierReason: "Long-duration service; manual shift pricing" },
  { serviceCode: "DAY_PROCEDURE", serviceName: "Day Surgery / Procedure Concierge", category: "Procedure & Treatment", serviceMultiplier: "1.20", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Procedure-day complexity and extended coordination" },
  { serviceCode: "PRE_SURGERY", serviceName: "Pre-Surgery Concierge", category: "Procedure & Treatment", serviceMultiplier: "1.10", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Preparation, records and multi-party coordination" },
  { serviceCode: "POST_SURGERY", serviceName: "Post-Surgery Follow-up", category: "Procedure & Treatment", serviceMultiplier: "1.00", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Standard follow-up journey with moderate coordination" },
  { serviceCode: "DIALYSIS", serviceName: "Dialysis Visit Concierge", category: "Recurring Treatment", serviceMultiplier: "0.90", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Recurring-service pricing; predictable workflow" },
  { serviceCode: "CHEMOTHERAPY", serviceName: "Chemotherapy Visit Concierge", category: "Recurring Treatment", serviceMultiplier: "1.00", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Recurring but higher emotional / coordination intensity" },
  { serviceCode: "RADIATION", serviceName: "Radiation Therapy Concierge", category: "Recurring Treatment", serviceMultiplier: "0.95", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Recurring treatment with relatively standardized workflow" },
  { serviceCode: "PHYSIO_REHAB", serviceName: "Physiotherapy / Rehab Visit", category: "Recurring Treatment", serviceMultiplier: "0.85", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Recurring, lower-complexity visit" },
  { serviceCode: "CHRONIC_FOLLOWUP", serviceName: "Chronic Care Follow-up", category: "Continuing Care", serviceMultiplier: "0.90", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Recurring care; predictable repeat workflow" },
  { serviceCode: "NRI_PARENT", serviceName: "NRI Parent Medical Concierge", category: "Continuing Care", serviceMultiplier: "1.20", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Premium family coordination, updates and trust layer" },
  { serviceCode: "SECOND_OPINION", serviceName: "Second Opinion Concierge", category: "Medical Coordination", serviceMultiplier: "0.85", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Coordination-heavy but limited physical journey complexity" },
  { serviceCode: "TELECONSULT", serviceName: "Teleconsultation Concierge", category: "Medical Coordination", serviceMultiplier: "0.65", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Remote / low travel intensity" },
  { serviceCode: "MEDICAL_RECORDS", serviceName: "Medical Records Concierge", category: "Medical Coordination", serviceMultiplier: "0.60", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Administrative coordination; limited physical accompaniment" },
  { serviceCode: "INSURANCE_TPA", serviceName: "Insurance / TPA Desk Concierge", category: "Medical Coordination", serviceMultiplier: "0.75", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Administrative coordination with moderate complexity" },
  { serviceCode: "HOSPITAL_TRANSFER", serviceName: "Hospital Transfer Concierge", category: "Medical Coordination", serviceMultiplier: "1.10", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Higher coordination and transfer responsibility" },
  { serviceCode: "REHAB_TRANSFER", serviceName: "Rehab / Nursing Facility Transfer", category: "Medical Coordination", serviceMultiplier: "1.05", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Transfer coordination with moderate risk and handover" },
  { serviceCode: "URGENT_COORDINATION", serviceName: "24×7 Urgent Care Coordination", category: "Urgent Coordination", serviceMultiplier: "1.30", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Urgent coordination premium; higher operational readiness" },
  { serviceCode: "DOCTOR_HOME_COORD", serviceName: "Doctor-at-Home Coordination", category: "Medical Coordination", serviceMultiplier: "0.85", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Coordination service; limited accompaniment" },
  { serviceCode: "NURSE_HOME_COORD", serviceName: "Nurse-at-Home Coordination", category: "Medical Coordination", serviceMultiplier: "0.85", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Coordination service; limited accompaniment" },
  { serviceCode: "MEDICAL_TOURISM_24H", serviceName: "Medical Tourism — Concierge Package (24 HR Basis)", category: "Medical Coordination", serviceMultiplier: "2.00", pricingMode: "MANUAL", numberOfAngels: 1, active: true, multiplierReason: "Future / manual packaged pricing; not standard MVP hourly logic" },
  { serviceCode: "PHARMACY_COORD", serviceName: "Pharmacy / Prescription Coordination", category: "Medical Coordination", serviceMultiplier: "0.65", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Low-complexity administrative / fulfilment coordination" },
  { serviceCode: "FAMILY_UPDATE", serviceName: "Family Medical Update Concierge", category: "Continuing Care", serviceMultiplier: "0.65", pricingMode: "AUTO", numberOfAngels: 1, active: true, multiplierReason: "Communication-focused support; no full physical journey" }
]);

export const serviceByCode = new Map(serviceMaster.map((service) => [service.serviceCode, service]));
